version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhostd:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   restart: always
  #   environment:
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #   volumes:
  #     - ./certs:/etc/nginx/certs:rw
  #     - ./vhostd:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx:latest
    restart: always
    expose:
      - "80"
    volumes:
      - ./src:/src:ro
      - ./config/nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${LOAN_DOCKER_WEBSITE},www.${LOAN_DOCKER_WEBSITE}
      - LETSENCRYPT_HOST=${LOAN_DOCKER_WEBSITE},www.${LOAN_DOCKER_WEBSITE}
      - LETSENCRYPT_EMAIL=${LOAN_DOCKER_EMAIL}
    links:
      - php
      - mysql

  php:
    image: php:fpm
    volumes:
      - ./src:/src
    links:
      - mysql

  mysql:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${LOAN_DOCKER_PASS_MYSQL}
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
